### PR TITLE
Fixed: `modelChangePostFixer` works correctly when item is moved out of container.

### LINKED ISSUE #78: Post fixer tries to use non-transformed changes.sourcePosition
`modelChangePostFixer` takes data from `model.Document#event:change` - `data.range` and `data.sourcePosition`. The `sourcePosition` is a value **before** the change happened. This means that if the change has moved some nodes before `sourcePosition`, the `sourcePosition` needs to be updated before it is used in the rest of algorithm.

### LINKED ISSUE #2993: Post fixer tries to use non-transformed changes.sourcePosition
`modelChangePostFixer` takes data from `model.Document#event:change` - `data.range` and `data.sourcePosition`. The `sourcePosition` is a value **before** the change happened. This means that if the change has moved some nodes before `sourcePosition`, the `sourcePosition` needs to be updated before it is used in the rest of algorithm.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed a bug when editor sometimes crashed when list item was moved outside and before a container in which it was. Closes ckeditor/ckeditor5#2993.

### CODE REVIEW

File: src/converters.js [hunk 1]
```diff
@@ -574,18 +574,25 @@ export function modelChangePostFixer( document ) {
 			return;
 		}
 
+		let sourcePos;
+
+		if ( changes.sourcePosition ) {
+			const howMany = changes.range.end.offset - changes.range.start.offset;
+			sourcePos = changes.sourcePosition._getTransformedByInsertion( changes.range.start, howMany, true );
+		}
```
Comment (pjasiun) [inline src/converters.js]: It looks like this variable can be used as undefined. Can you move it to `type == 'remove'`  and `type == 'move'`?
