### PR TITLE
Fixed: <ul> and <ol> elements now will not be inserted before view ui elements

### LINKED ISSUE #71: <ul> and <ol> elements are inserted before ui elements
Assume this view state:
```html
<ul>
  <li>Foo<span class="myUi"></span></li>
  <li>Bar</li>
</ul>
```

Now, a user indents second item. What happens then is:
1. `<li>Bar</li>` is extracted.
2. It is wrapped into `<ul>`.
3. It is inserted into view, inside "Foo" `<li>`.

Unfortunately it is inserted at wrong position. Lists have that characteristic, that in `<li>`, no other node should be after `<ul>` or `<ol>`. When insertion position is mapped from model to view, it is before `Foo` text node and `<span>` ui element. The result is this:

```html
<ul>
  <li>
    Foo
    <ul>
      <li>Bar</li>
    </ul>
    <span class="myUi"></span>
  </li>
</ul>
```
This is a very different structure. Now ui element is not "after `Foo`" but "after `Bar`". Also, depending on CSS styles, it may display in a weird way.

### LINKED ISSUE #2990: <ul> and <ol> elements are inserted before ui elements
Assume this view state:
```html
<ul>
  <li>Foo<span class="myUi"></span></li>
  <li>Bar</li>
</ul>
```

Now, a user indents second item. What happens then is:
1. `<li>Bar</li>` is extracted.
2. It is wrapped into `<ul>`.
3. It is inserted into view, inside "Foo" `<li>`.

Unfortunately it is inserted at wrong position. Lists have that characteristic, that in `<li>`, no other node should be after `<ul>` or `<ol>`. When insertion position is mapped from model to view, it is before `Foo` text node and `<span>` ui element. The result is this:

```html
<ul>
  <li>
    Foo
    <ul>
      <li>Bar</li>
    </ul>
    <span class="myUi"></span>
  </li>
</ul>
```
This is a very different structure. Now ui element is not "after `Foo`" but "after `Bar`". Also, depending on CSS styles, it may display in a weird way.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: `<ul>` and `<ol>` view elements now will not be inserted before view ui elements. Closes ckeditor/ckeditor5#2990.

### CODE REVIEW

**Comment by Reinmar** [comment]
So elegant :)

**Comment by scofalik** [comment]
You appreciate commit, title and merge message having (almost) same wording?

**Comment by Reinmar** [comment]
The minimal changes in the code.

File: src/converters.js [hunk 1]
```diff
@@ -885,6 +885,8 @@ function injectViewList( modelItem, injectedItem, mapper, removePosition ) {
 		}
 	}
 
+	insertPosition = positionAfterUiElements( insertPosition );
```
Comment (Reinmar) [inline src/converters.js:888]: Can't it simply be a position at the end of `<li>`? I don't think we suppose to have anything else after a nested `<ul>`?

Comment (scofalik) [reply src/converters.js:888]: It's not always a position at the end of `<li>`. Sometimes it is between two `<ul>`s (that's when `<ul>` is broken to make a place injected `<ul><li>...</li></ul>` structure). Sometimes weird cases happen.

I know it sounds easy: "just find correct `<li>` and insert the list at the end of it, DUH? O_O", but writing those converters wouldn't take weeks if it was so.

I remember time when positions were created a lot "at the end of `<li>`" and it lead to weird problems.

Let's say you have a `<li>` with `<ul>` and then you try to inject view list item. But you have to inject it before that `<ul>` not after, because this is how they are ordered in model. You cannot set the insert position to the end, because something (`<ul>`) may already be there and that would be incorrect.

So, just believe me that the way it is, is a safe way :). We could refactor this for ages, probably. I just did it like this because I am (pretty) sure that this way there's least possibility to break anything.

Comment (Reinmar) [reply src/converters.js:888]: I just asked :P Out of curiosity, to gain knowledge and thus increase the bus factor ;)

Comment (scofalik) [reply src/converters.js:888]: Sorry, my sensors are down lately.
