### PR TITLE
Fixed: List postfixers should check if attribute is allowed od elemen…

### LINKED ISSUE #103: List postfixers should always check `type` attribute and type of element.
The `type` attribute has a general name that might be used in other features. One such a feature was [created here](https://github.com/ckeditor/ckeditor5/issues/1010#issue-319168252). Basically it adds a `type` attribute on `video` model element which represents the type of a media, ie `video/mp4`.

Unfortunately using it with conjunction with the `List` features leads to removing `type` attribute from a `video` element by List postfixer:

https://github.com/ckeditor/ckeditor5-list/blob/8074189abd6b406c02edd697556a267b8ae4e053/src/converters.js#L600-L620

The problem is that it should also if `item` is a `listItem` as in other checks.

### LINKED ISSUE #3003: List postfixers should always check `type` attribute and type of element.
The `type` attribute has a general name that might be used in other features. One such a feature was [created here](https://github.com/ckeditor/ckeditor5/issues/1010#issue-319168252). Basically it adds a `type` attribute on `video` model element which represents the type of a media, ie `video/mp4`.

Unfortunately using it with conjunction with the `List` features leads to removing `type` attribute from a `video` element by List postfixer:

https://github.com/ckeditor/ckeditor5-list/blob/8074189abd6b406c02edd697556a267b8ae4e053/src/converters.js#L600-L620

The problem is that it should also if `item` is a `listItem` as in other checks.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Rename list attributes `indent` and `type` to `listIndent` and `listType`. Closes ckeditor/ckeditor5#3003.

BREAKING CHANGE: The `indent` attribute is now called `listIndent`. See ckeditor/ckeditor5#3003 for more information.
BREAKING CHANGE: The `type` attribute is now called `listType`. See ckeditor/ckeditor5#3003 for more information.

---

### Additional information

* It addresses the issue with `<video type="">` issue. But it should be fixed by schema itself.
* Requires changes in other repos:
    * https://github.com/ckeditor/ckeditor5-alignment/tree/t/ckeditor5-list/103
    * https://github.com/ckeditor/ckeditor5-autoformat/tree/t/ckeditor5-list/103
    * https://github.com/ckeditor/ckeditor5-block-quote/tree/t/ckeditor5-list/103
    * https://github.com/ckeditor/ckeditor5-engine/tree/t/ckeditor5-list/103
    * https://github.com/ckeditor/ckeditor5-typing/tree/t/ckeditor5-list/103

### CODE REVIEW

File: src/converters.js [hunk 1]
```diff
@@ -602,13 +602,15 @@ export function modelChangePostFixer( model, writer ) {
 				// In case of renamed element.
 				const item = entry.position.nodeAfter;
 
-				if ( item.hasAttribute( 'indent' ) ) {
+				// Only remove 'indent' attribute from items that doesn't allow such attribute. #103
```
Comment (Reinmar) [inline src/converters.js]: Could you add a comment that this code should be removed once https://github.com/ckeditor/ckeditor5-engine/issues/1228 is resolved?

Comment (jodator) [reply src/converters.js]: The whole check, am I right?

Comment (jodator) [reply src/converters.js]: done

**Comment by Reinmar** [comment]
As discussed in https://github.com/ckeditor/ckeditor5-list/issues/103#issuecomment-389079136 we should rather change the name of list item's attributes. Those attrs which are only used with list items should be prefixed.

**Comment by jodator** [comment]
@Reinmar OK I've changed the PR to renaming `type` to `listType` and `indent` to `listIndent`.

**Comment by Reinmar** [comment]
What about other repos?

**Comment by jodator** [comment]
> What about other repos?

Do you mean like docs in `model/schema` which uses lists as examples or some other things? I'll update the docs but for the latter you have give me some more hints ;)

ps.: OK I've found some tests in other repos to update also

**Comment by Reinmar** [comment]
> ps.: OK I've found some tests in other repos to update also
> 

Yup, I meant the tests.

**Comment by jodator** [comment]
@Reinmar so it's done - see updated PR comment with proper branches.
