### PR TITLE
Fixed: `view.UIElement` should be properly handled in list remove converter

### LINKED ISSUE #74: List remove converter does not handle UI elements properly
`modelViewRemove` - list remove converter does not handle UI elements properly.

```javascript
const viewPosition = conversionApi.mapper.toViewPosition( data.sourcePosition );
const viewItem = viewPosition.nodeAfter.is( 'li' ) ? viewPosition.nodeAfter : viewPosition.nodeAfter.getChild( 0 );
```

In the second line, the converter expects that the node after view position is either `<li>` or `<ul>`/`<ol>`. It could be, however, a UI element.

### LINKED ISSUE #2991: List remove converter does not handle UI elements properly
`modelViewRemove` - list remove converter does not handle UI elements properly.

```javascript
const viewPosition = conversionApi.mapper.toViewPosition( data.sourcePosition );
const viewItem = viewPosition.nodeAfter.is( 'li' ) ? viewPosition.nodeAfter : viewPosition.nodeAfter.getChild( 0 );
```

In the second line, the converter expects that the node after view position is either `<li>` or `<ul>`/`<ol>`. It could be, however, a UI element.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: `view.UIElement` will no longer be incorrectly removed instead of `<li>` element if it was before `<li>` element to remove. Closes ckeditor/ckeditor5#2991.

### CODE REVIEW

File: tests/listengine.js [hunk 1]
```diff
@@ -3345,6 +3345,45 @@ describe( 'ListEngine', () => {
...
+			beforeEach( () => {
+				editor.setData( '<ul><li>Foo</li><li>Bar</li></ul>' );
+				uiElement = new ViewUIElement( 'span' );
+			} );
+
+			it( 'ui element before <ul>', () => {
+				// Append ui element before <ul>.
+				viewRoot.insertChildren( 0, [ uiElement ] );
+
+				modelDoc.batch().remove( modelRoot.getChild( 0 ) );
```
Comment (Reinmar) [inline tests/listengine.js]: Uh... it took me 30s to understand this test. It wasn't clear for me until I understood that `getChild( 0 )` is `<listItem>Foo</listItem>`. Please comment such lines.

**Comment by scofalik** [comment]
Done
