### PR TITLE
Fix: Backspace at first LI should not merge with previous block.

### LINKED ISSUE #68: Backspace at first LI should not merge with previous block
Starting HTML:

```
<p>Text in paragraph</p>
<ol>
    <li>^Item 1</li>
    <li>Item 2</li>
</ol>
```

Current results after Backspace:

```
<p>Text in paragraph^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

Expected results:

```
<p>Text in paragraph</p>
<p>^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

### LINKED ISSUE #2987: Backspace at first LI should not merge with previous block
Starting HTML:

```
<p>Text in paragraph</p>
<ol>
    <li>^Item 1</li>
    <li>Item 2</li>
</ol>
```

Current results after Backspace:

```
<p>Text in paragraph^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

Expected results:

```
<p>Text in paragraph</p>
<p>^Item 1</p>
<ol>
    <li>Item 2</li>
</ol>
```

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Pressing <kbd>Backspace</kbd> at the beginning of a first list item will turn it into a paragraph instead of merging with the previous block. Closes ckeditor/ckeditor5#2987.

---

### Additional information

* I didn't dig much into `getFirstPosition`/`getLastPosition` difference in this scenario so I'll read about this more later since I didn't catch the difference here if `selection.isCollapsed`
* probably some comments are needed as there are many  cases to check for this particular case which should only listen to `backspace` not `delete` on collapsed selection and only in first item of list.

### CODE REVIEW

File: src/list.js [hunk 1]
```diff
@@ -61,6 +61,28 @@ export default class List extends Plugin {
 			}
 		} );
 
+		// Overwrite default Backspace key behavior.
+		// If Backspace key is pressed with selection collapsed on first position in first list item, outdent it.
```
Comment (Reinmar) [inline src/list.js]: Please add ref to a ticket (simple "... outdent it. #83")

File: tests/list.js [hunk 2]
```diff
@@ -116,6 +116,68 @@ describe( 'List', () => {
...
+			sinon.spy( editor, 'execute' );
+
+			setData( doc, '<listItem type="bulleted" indent="0">fo[]o</listItem>' );
+
+			editor.editing.view.fire( 'delete', domEvtDataStub );
+
+			sinon.assert.notCalled( editor.execute );
+		} );
+
+		it( 'should not execute outdentList command on delete key in first item of list', () => {
```
Comment (Reinmar) [inline tests/list.js]: Actually, compare this with CKE4 – it will outdent even at the beginning of the document.

Comment (Reinmar) [reply tests/list.js]: Ah, sorry - this is forward delete's test. In such case, the description is wrong.

File: src/list.js [hunk 3]
```diff
@@ -61,6 +61,28 @@ export default class List extends Plugin {
...
+		this.listenTo( this.editor.editing.view, 'delete', ( evt, data ) => {
```
Comment (Reinmar) [inline src/list.js]: As for this callback – I propose to refactor it a bit. Instead of one big `if()` let's have early returns. Why? The reason is performance aspect. If we have to access so many properties and calculate so many values on every <kbd>Backspace</kbd> we're increasing memory pressure and risking glitches.

Another thing is that we need to include two more cases here – when a list is nested (in a blockQuote e.g.) and when the block before is nested in a blockQuote.

Like:

```html
<bQ><p>x</p></bQ><listItem>[]y</listItem>

<p>x</p><bQ><listItem>[]y</listItem></bQ>
```

Please write tests for them. I think those cases will work fine with the current code, but just to be sure.

**Comment by Reinmar** [comment]
> I didn't dig much into getFirstPosition/getLastPosition difference in this scenario so I'll read about this more later since I didn't catch the difference here if selection.isCollapsed

It's the same position if selection is collapsed.

> probably some comments are needed as there are many cases to check for this particular case which should only listen to backspace not delete on collapsed selection and only in first item of list.

Not necessarily – the code reads fine.

---

R- cause there are two missing tests and because we can improve that callback a bit. But in general, the solution looks good.
